package com.varyfi.exampe.demovirfay.entity;
// Generated Dec 13, 2020 8:54:05 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="numvrity"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String number;
     private String valid;
     private String localFormat;
     private String internationalFormat;
     private String countryPrefix;
     private String countryCode;
     private String countryName;
     private String location;
     private String carrier;
     private String lineType;

    public User() {
    }

	
    public User(String valid) {
        this.valid = valid;
    }
    public User(String number, String valid, String localFormat, String internationalFormat, String countryPrefix, String countryCode, String countryName, String location, String carrier, String lineType) {
       this.number = number;
       this.valid = valid;
       this.localFormat = localFormat;
       this.internationalFormat = internationalFormat;
       this.countryPrefix = countryPrefix;
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.location = location;
       this.carrier = carrier;
       this.lineType = lineType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="number", length=20,unique = true)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="valid", nullable=false, length=20)
    public String getValid() {
        return this.valid;
    }
    
    public void setValid(String valid) {
        this.valid = valid;
    }

    
    @Column(name="local_format", length=100)
    public String getLocalFormat() {
        return this.localFormat;
    }
    
    public void setLocalFormat(String localFormat) {
        this.localFormat = localFormat;
    }

    
    @Column(name="international_format", length=100)
    public String getInternationalFormat() {
        return this.internationalFormat;
    }
    
    public void setInternationalFormat(String internationalFormat) {
        this.internationalFormat = internationalFormat;
    }

    
    @Column(name="country_prefix", length=100)
    public String getCountryPrefix() {
        return this.countryPrefix;
    }
    
    public void setCountryPrefix(String countryPrefix) {
        this.countryPrefix = countryPrefix;
    }

    
    @Column(name="country_code", length=100)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="country_name", length=100)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="location", length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="carrier", length=100)
    public String getCarrier() {
        return this.carrier;
    }
    
    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    
    @Column(name="line_type", length=100)
    public String getLineType() {
        return this.lineType;
    }
    
    public void setLineType(String lineType) {
        this.lineType = lineType;
    }




}


